name: zapfull-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-baseline@v0.6.1
      with:
        target: "https://stafftravel.globalxair.com"
        allow_issue_writing: 'false'
        artifact_name: 'test_zapscan'
          
