# name: zapfull-security-scan
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:     
#     - name: OWASP ZAP Full Scan
#       uses: zaproxy/action-baseline@v0.6.1
#       with:
#         target: "https://stafftravel.globalxair.com"
#         allow_issue_writing: 'false'
#         artifact_name: 'test_zapscan'
name: zapfull-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          target: 'https://rajeshwar.cloud'
        #  rules_file_name: '.zap/rules.tsv'
        #  cmd_options: '-a'
